import Head from 'next/head';
import styles from 'styles/home.module.css';
import { Footer } from 'components/footer/footer';
import {Figtree} from '@next/font/google'

const font = Figtree();

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app"/>
        <link rel="icon" href="/favicon.ico"/>
      </Head>
      <Footer/>
    </div>
  );
}
